#!/bin/sh
#
# model_defn.sh
#
# Automatically generates a Python module that defines all of the model
# parameters and variables, to allow inspection and alteration of the model
# state.
#

OUTFILE=model_defn.py

PARAMS_LIST="../src/params.lst"
VARS_LIST="../src/vars.lst"

#
# Ensure that the necessary data files can be read.
#

if [ ! -r ${PARAMS_LIST} ]; then
    echo "ERROR: parameters file ${PARAMS_LIST} is not readable."
    exit 2
fi

if [ ! -r ${VARS_LIST} ]; then
    echo "ERROR: variables file ${VARS_LIST} is not readable."
    exit 2
fi

#
# Build the Python module.
#

# Module description.
cat > ${OUTFILE} <<EOF
"""This module is automatically generated by model_defn.sh.
It defines all of the model parameters and variables.
"""
EOF

echo '' >> ${OUTFILE}

# Required import of the 'ctypes' module.
echo 'from ctypes import *' >> ${OUTFILE}

echo '' >> ${OUTFILE}

# Define the 'MPARAMS' struct, which holds the model parameters.
echo 'class MPARAMS(Structure):' >> ${OUTFILE}
echo '  """The model parameters."""' >> ${OUTFILE}
echo '  _fields_ = [' >> ${OUTFILE}
# Print each parameter as: '    ("name", c_double),'.
cat ${PARAMS_LIST} |
  awk '{ print "    (\"" $1 "\", c_double)," }' >> ${OUTFILE}
echo '  ]' >> ${OUTFILE}

echo '' >> ${OUTFILE}

# Define the 'MVARS' struct, which holds the model variables.
echo 'class MVARS(Structure):' >> ${OUTFILE}
echo '  """The model variables."""' >> ${OUTFILE}
echo '  _fields_ = [' >> ${OUTFILE}
# Print each variable as: '    ("name", c_double),'.
cat ${VARS_LIST} |
  awk '{ print "    (\"" $1 "\", c_double)," }' >> ${OUTFILE}
echo '  ]' >> ${OUTFILE}
