#!/bin/bash
#
# params.sh
#
# Automatically generates C++ code for constructing and initialising a struct
# of all model parameters, and for setting the values of individual parameters
# by name.
#
# This script produces the following files:
#   * params.h   -- Defines the PARAMS type, set_param() and PARAMS_INIT.
#   * params.cpp -- Implements the set_param() function.
#
# NOTE: This script requires the file "params.lst" to contain all of the model
#       parameter names, each on a separate line, and the file "params.val" to
#       contain the default parameter values, each on a separate line.
#

#
# The files that are processed/generated by this script.
#
PARAMS_LIST="params.lst"
PARAMS_VALS="params.val"
PARAMS_DEFN="params.h"
PARAMS_CODE="params.cpp"

#
# Check whether the list of parameter names exists and is readable.
#
if [ ! -f ${PARAMS_LIST} ]; then
  echo "ERROR: input file ${PARAMS_LIST} does not exist."
  exit 2;
fi

if [ ! -r ${PARAMS_LIST} ]; then
  echo "ERROR: input file ${PARAMS_LIST} is not readable."
  exit 2;
fi

#
# Check whether the list of parameter values exists and is readable.
#
if [ ! -f ${PARAMS_VALS} ]; then
  echo "ERROR: input file ${PARAMS_VALS} does not exist."
  exit 2;
fi

if [ ! -r ${PARAMS_VALS} ]; then
  echo "ERROR: input file ${PARAMS_VALS} is not readable."
  exit 2;
fi

#
# Build the header file.
#
cat ${PARAMS_LIST} |
  awk 'BEGIN { print "struct PARAMS {"; } ;
       { print "double " $1 ";" } ;
       END { print "};"; }' > ${PARAMS_DEFN}

echo "void set_param(PARAMS &p, const char *name, double value);" >> ${PARAMS_DEFN}

PARAM_COUNT=`wc -l ${PARAMS_LIST} | awk '{ print $1; }'`
echo "#define PARAM_COUNT ${PARAM_COUNT}" >> ${PARAMS_DEFN};

#
# Produce the code fragment that will initialise the parameters.
#
echo "#define PARAMS_INIT(p) do { \\" >> ${PARAMS_DEFN}

cat ${PARAMS_VALS} |
  awk '{ print "\tp."$1 " = " $2 "; \\"; }' >> ${PARAMS_DEFN}

echo "} while (0)" >> ${PARAMS_DEFN}

#
# Build the code for set_param().
#
echo '#include <stdio.h>' > ${PARAMS_CODE}
echo '#include <string.h>' >> ${PARAMS_CODE}
echo '#include "params.h"' >> ${PARAMS_CODE}
echo '' >> ${PARAMS_CODE}

cat ${PARAMS_LIST} |
  awk 'BEGIN { print "void set_param(PARAMS &p, const char *name, double value) {"; };
       { print "  if (! strcmp(name, \"" $1 "\")) {";
         print "    p." $1 " = value;";
         print "    return;"
         print "  }"; }
       END { print "  fprintf(stderr, \"ERROR: Unknown parameter name \\\"%s\\\"\\n\", name);";
             print "}"; };' >> ${PARAMS_CODE}
